testsite1/notinator/urls.py
from django.urls import path
from . import views

app_name = 'notinator'
urlpatterns = [
    # ex: /polls/
    path('', views.homepage, name='homepage'),
    path('results/', views.results, name='results'),
    path('results/quiz/<int:quiz_id>/', views.quiz, name='quiz'),
    path('results/resoures/<int:resource_list_id>/', views.resources, name='resources'),
]

testsite1/testsite1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('notinator.urls')),
    # path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('notinator/', include('notinator.urls')),
]

testsite1/notinator/models.py
from django.db import models


# Create your models here.

class ResourceList(models.Model):
    """
    fields: resouces_name, resources_description, resources_image,
        resource_subject, resources_misc_text, resources, on_subject_index
    methods: make_resources
    """

    subject = models.CharField(max_length=100, default='null_subject')
    on_subject_index = models.IntegerField(default=0)

    name = models.CharField(max_length=100, default='null_name')
    description = models.CharField(max_length=100, default='null_descriptor')
    image = models.ImageField(upload_to='notinator/resources_images/', default='notinator/resources_images/default.png')

    misc_text = models.CharField(max_length=5000, default='null_text')

    class Index:
        indexes = [
            models.Index(fields=['subject' + 'on_subject_index'], name='resources_subject_index')
        ]


class Resource(models.Model):
    name = models.CharField(max_length=20, default='null_name')
    description = models.CharField(max_length=200, default='null_description')
    r_link = models.URLField(max_length=200, default='null_link')
    resource_list = models.ForeignKey(ResourceList, on_delete=models.CASCADE)


class Quiz(models.Model):
    """
    fields: quiz_subject, quiz_name, quiz_description,
        quiz_image, question_amount, questions, on_subject_index, misc_text
    methods: make_quiz
    """

    subject = models.CharField(max_length=100, default='null_subject')
    on_subject_index = models.IntegerField(default=0)

    name = models.CharField(max_length=100, default='null_name')
    description = models.CharField(max_length=100, default='null_description')
    image = models.ImageField(upload_to='notinator/quiz_images/', default='notinator/quiz_images/default.png')

    misc_text = models.CharField(max_length=200, default='null_text')

    class Index:
        indexes = [
            models.Index(fields=['subject' + 'on_subject_index'], name='quiz_subject_index'),
        ]


class QuizQuestion(models.Model):
    base_question = True
    multiple_choice_question = False

    name = models.CharField(max_length=200, default='null_name')
    body = models.CharField(max_length=200, default='null_body')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    def mark(self, answer: str) -> bool:
        return False

    def get_feedback(self, answer: str) -> str:
        return 'null_feedback'


class QQMultipleChoice(QuizQuestion):
    base_question = False
    multiple_choice_question = True

    choices = list[models.CharField(max_length=200)]
    answer = models.CharField(max_length=200)

    def mark(self, answer: str) -> bool:
        return str == self.answer

    def get_feedback(self, answer: str) -> str:
        if self.mark(answer):
            return 'correct'
        else:
            return format('incorrect. Correct Answer: {}', answer)

testsite1/notinator/forms.py
from django import forms
from .models import Quiz, QuizQuestion
from django.utils.safestring import mark_safe


class InputForm(forms.Form):
    text = forms.CharField(
        label='Input',
        max_length=3000,
        initial='Enter your text and links here',
        required=True)

    selection = forms.ChoiceField(
        choices=(('1', 'Quiz'), ('2', 'Resources')),
        label='Choose a result',
        required=True)

    override_make_new = forms.BooleanField(
        label='Always create new result',
        required=False)


class QuizForm(forms.Form):
    def __init__(self, quiz_arg: Quiz, *args, **kwargs):
        super(QuizForm, self).__init__(*args, **kwargs)
        self.quiz = quiz_arg

        # assert form_quiz_object.questions is list[Quiz.QuizQuestion]
        for i, question in enumerate(QuizQuestion.objects.filter(quiz=self.quiz)):

            if question.base_question:
                # Base question
                self.fields[question.name] = forms.CharField(
                    label=mark_safe('Question: ' + str(i) + '<br />' + question.name + '<br />' + question.body),
                    max_length=200,
                    initial='enter your answer here',
                    required=True)

            if question.multiple_choice_question:
                # this is for multiple choice, support for other types will be added later
                self.fields[question.name] = \
                    forms.ChoiceField(
                        choices=question.choices,
                        label=mark_safe('Question: ' + str(i) + '<br />' + question.name + '<br />' + question.body),
                        required=True)

    def mark(self):
        print("test success")

        question: QuizQuestion
        for i, question in enumerate(QuizQuestion.objects.filter(quiz=self.quiz)):
            print("test success2")

            answer = self.cleaned_data[question.name]

            if question.multiple_choice_question:
                # this is for multiple choice, support for other types will be added later
                answer = self.cleaned_data[question.name]

            self.fields[question.name].required = False
            label = self.fields[question.name].label
            self.fields[question.name].label = \
                mark_safe("Question: {} <br /> Your answer: {} <br /> Feedback: {}".format(
                    label, answer, question.get_feedback(answer)))

testsite1/notinator/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import models

from .forms import InputForm, QuizForm
from .models import Quiz, ResourceList, QuizQuestion, Resource, QQMultipleChoice


def homepage(request):
    if request.method == 'POST':
        form = InputForm(request.POST)
        if form.is_valid():
            selection: int = int(form.cleaned_data['selection'])

            if 0 < selection < 3:
                subject = 'Addition'
                # todo: get subject from func call, as well as amount of resources/questions

                # get a list of already-made resources
                resource_lists: models.QuerySet = ResourceList.objects.filter(subject=subject)

                # if there are no resources, create one
                if len(resource_lists) == 0 or form.cleaned_data['override_make_new']:

                    # todo: get resource body from function call
                    new_resource = ResourceList(subject=subject, on_subject_index=len(resource_lists))
                    new_resource.save()

                    Resource(resource_list=new_resource, name='Wikipedia', description='',
                             r_link='https://en.wikipedia.org/wiki/Addition').save()
                    Resource(resource_list=new_resource, name='Cambridge', description='',
                             r_link='https://dictionary.cambridge.org/dictionary/english/addition').save()

                else:
                    new_resource = resource_lists[0]

                # if the user requested a quiz, get that
                if selection == 1:
                    # todo: get quiz from resource_list
                    quiz_lists: models.QuerySet = Quiz.objects.filter(subject=subject)

                    new_quiz = Quiz(subject=subject, on_subject_index=len(quiz_lists))
                    new_quiz.save()

                    QuizQuestion(quiz=new_quiz, name='What is addition?', body='').save()
                    choices1 = ['The Chinese', 'The Egyptians', 'The Babylonians', 'The Italians']
                    q = QQMultipleChoice(quiz=new_quiz, name='Who is credited with inventing addition?', body='',
                                         answer='')
                    q.choices = choices1
                    q.save()

                    # todo: store the dict of resource/quiz and indexes somewhere and use it
                    return HttpResponseRedirect(reverse('notinator:quiz', args=(new_quiz.id,)))

                return HttpResponseRedirect(reverse('notinator:resources', args=(new_resource.id,)))

            else:
                return HttpResponseRedirect(reverse('notinator:homepage'), {'form': form})

    else:
        form = InputForm()

    return render(request, 'notinator/homepage.html', {'form': form})


def quiz(request, quiz_id):
    selected_quiz = get_object_or_404(pk=quiz_id, klass=Quiz.objects.all())

    if request.method == 'POST':
        form = QuizForm(data=request.POST, quiz_arg=selected_quiz)
        if form.is_valid():
            form.mark()
            return render(request, 'notinator/quizresults.html', context={'form': form})
        else:
            return render(request, 'notinator/nosubmission.html')

    form = QuizForm(selected_quiz)

    return render(request, 'notinator/quizpage.html',
                  context={'form': form, 'path': ('/results/quiz/' + str(quiz_id) + '/')})


def resources(request, resource_list_id):
    resource_list = get_object_or_404(pk=resource_list_id, klass=ResourceList.objects.all())

    return render(request, 'notinator/resourcepage.html',
                  context={'resource_list': resource_list,
                           'resources': Resource.objects.filter(resource_list=resource_list)})


# Create your views here.
def results(request):
    return homepage(request)


""""{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'notinator/style.css' %}">"""

testsite1/notinator/templates/notinator/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        {% load static %}
    <link rel="shortcut icon" href="{% static 'notinator/favicon.ico' %}" type="image/x-icon">


    <title>Notinator | Home</title>
</head>
<boy><img src="{% static 'notinator/notinator_logo.png' %}" alt="Notinator"></boy>
<boy2><img src="{% static 'notinator/notinator_logo.png' %}" alt="Notinator"></boy2>

<body>
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'notinator/style.css' %}">

<h1>Notinator</h1>
<h3>Study Helper</h3>
<p><l>
    Notinator is an online tool designed to aid student's lives.</l></p>

    <p><k>We help student cut through the ever-growing fog of online
        information to get the information they need to succeed.</k></p>

    <p><m>In addition, we provide tools for students to test their knowledge
    and improve their skills.
</m></p>

<h5>Get started by inputting anything!</h5>

<form action="results/" method="post">
    {% csrf_token %}
    <table>
    <tr>
    <th><label for="id_text">Input:</label></th>
    <td>
      <input type="text" name="text" value="Enter your text and links here" maxlength="3000" required id="id_text">
    </td>
  </tr>
  <tr>
    <th><label for="id_selection">Choose a result:</label></th>
    <td>
      <select name="selection" id="id_selection">
  <option value="1">Quiz</option>
  <option value="2">Resources</option>
</select>
    </td>
  </tr>
  <tr>
    <th><label for="id_override_make_new">Always create new result:</label></th>
    <td>
      <input type="checkbox" name="override_make_new" id="id_override_make_new">
    </td>
  </tr>
                </table>
<heheheha>
    <input type="submit" value="Submit">
    </heheheha>
</form>
</body>
</html>

testsite1/notinator/templates/notinator/nosubmission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        {% load static %}
    <link rel="shortcut icon" href="{% static 'notinator/favicon.ico' %}" type="image/x-icon">


    <title>Notinator</title>
</head>
<body>
<boy><img src="{% static 'notinator/notinator_logo.png' %}" alt="Notinator"></boy>
<boy2><img src="{% static 'notinator/notinator_logo.png' %}" alt="Notinator"></boy2>

{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'notinator/style.css' %}">

<h1>Notinator</h1>

<p>invalid form submission</p>

<a href="/"><hl> Back to Home</hl></a>
</body>
</html>

testsite1/notinator/templates/notinator/quizpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        {% load static %}
    <link rel="shortcut icon" href="{% static 'notinator/favicon.ico' %}" type="image/x-icon">


    <title>Notinator | Quiz</title>
</head>
<body>
<boy><img src="{% static 'notinator/notinator_logo.png' %}" alt="Notinator"></boy>
<boy2><img src="{% static 'notinator/notinator_logo.png' %}" alt="Notinator"></boy2>

{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'notinator/style.css' %}">

<h1>Notinator</h1>
<p>AI-Generated Quizzes to test your knowledge! </p>
<form action={{ path }} method="post">
    {% csrf_token %}
    <table>
    {{ form }}
        </table>
    <heheheha>
    <input type="submit" value="Submit">
        </heheheha>
</form>

<a href="/"><hl> Back to Home</hl></a>

</body>

</html>

testsite1/notinator/templates/notinator/quizresults.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        {% load static %}
    <link rel="shortcut icon" href="{% static 'notinator/favicon.ico' %}" type="image/x-icon">


    <title>Notinator | Results</title>
</head>
<body>
<boy><img src="{% static 'notinator/notinator_logo.png' %}" alt="Notinator"></boy>
<boy2><img src="{% static 'notinator/notinator_logo.png' %}" alt="Notinator"></boy2>

{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'notinator/style.css' %}">

<h1>Notinator</h1>
<p>Quiz Results: </p>
<h5>Note: you will not be able to see these after you close the page</h5>

<form action={{ path }} method="post">
    {% csrf_token %}
    <table>
    {{ form }}
        </table>
</form>

<a href="/"><hl> Back to Home</hl></a>
</body>
</html>

testsite1/notinator/templates/notinator/resourcepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        {% load static %}
    <link rel="shortcut icon" href="{% static 'notinator/favicon.ico' %}" type="image/x-icon">


    <title>Notinator | Resources</title>
</head>
<body>
<boy><img src="{% static 'notinator/notinator_logo.png' %}" alt="Notinator"></boy>
<boy2><img src="{% static 'notinator/notinator_logo.png' %}" alt="Notinator"></boy2>

{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'notinator/style.css' %}">

<h1>Notinator</h1>

<h3> We found these resources relating to your subject: {{resource_list.subject}}</h3>

<!-- <h5>{{resource_list.name}}<br></h5>
    <legend><h5>{{resource_list.description}}<br></h5></legend> -->
    {% for choice in resources %}
<h6>{{choice.name}}<br></h6>
        <p><rssdesc>{{choice.description}}<br></rssdesc></p>
        <a><rsslink>{{choice.url}}<br></rsslink></a>
    {% endfor %}
<a href="/"><hl> Back to Home</hl></a>
</body>
</html>